# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:

- task: UiPathPack@2
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)'
    outputType: 'Process'
    orchestratorConnection: 'UiPath Main Tenant'
    outputPath: '$(Build.ArtifactStagingDirectory)\Output'

- task: UiPathTest@2
  inputs:
    testTarget: 'TestProject'
    orchestratorConnection: 'UiPath Main Tenant'
    testProjectPath: '$(Build.SourcesDirectory)'
    folderName: 'ModernFolderDefault'

- task: UiPathDeploy@2
  inputs:
    orchestratorConnection: 'UiPath Main Tenant'
    packagesPath: '$(Build.ArtifactStagingDirectory)\Output'
    folderName: 'ModernFolderDefault'
  condition: succeeded()